import Head from 'next/head';
import Image from 'next/image';
import styles from './styles.module.css';
import { LeftSide, RightSide } from '@/components/index';
import HomeNavigation from '@/components/home/homeNavigation';
import { useState } from 'react';
import { ArrowForwardRounded } from '@material-ui/icons';
import UserStatusInput from '@/components/home/userStatusInput';
import PersonCard from '@/components/home/personCard';
import { posts } from '@/dummyData/posts.json';
import Post from '@/components/home/post';
import { recommendedFriends } from '@/dummyData/recommendedFriends.json';
import appPages from '@/shared/appPages';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <LeftSide currentPage={appPages.home} />
        <div className={styles.contentContainer}>
          <HomeNavigation />
          <UserStatusInput />
          <div className={styles.recommendedPeople}>
            <div className={styles.cardListHeader}>
              <p>Follow People</p>
              <ArrowForwardRounded style={{ cursor: 'pointer' }} />
            </div>
            <div className={styles.recommendList}>
              {recommendedFriends.map((person) => {
                return <PersonCard key={person.id} {...person} />;
              })}
            </div>
          </div>
          <div className={styles.listPost}>
            {posts.map((post) => (
              <Post key={post.id} {...post} />
            ))}
          </div>
        </div>
        <RightSide />
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
